const User =require("../Models/User")
const mailSender=require("../Utils/mailSender")
const crypto =require("crypto");
const bcrypt =require("bcrypt");


//reset password Token
exports.resetPasswordToken=async(req,res)=>{
    try{
        //get email from body
        const email=req.body.email;
        if(!email){
            return res.status(401).json({
                success:false,
                message:"Email required"
            })
        }
        // console.log("Email for resetting password token ", email);
        const user=await User.findOne({email});
        if(!user){
            return res.status(401).json({
                success:false,
                message:"User not registered with us",
            })
        }
        //generate token
        const token=crypto.randomUUID();
        // console.log("Token generated by crypto ",token);
        // add token to user database and its expiry time
        const updatedDetails=await User.findOneAndUpdate({email:email},{
            
                token:token,
                resetPasswordExpires: Date.now()+5*60*1000,
        },{new:true});
        // console.log("Consoling updatedUser while setting its token ::",updatedDetails);
        //create Url
        // console.log("Token is:: ",updatedDetails.token,updatedDetails.resetPasswordExpires);

        const url=`http://localhost:3000/update-password/${token}`;

        //send mail containing url 
        // console.log("Consoling the reset password token link :",url);
        await mailSender(email,"Password Reset Link ",`Password Reset Link${url}`);
        return res.status(200).json({
            success:true,
            message:"Email Sent successfully, please check your email",
        })
    }
    catch(e){
        console.log(e);
        return res.status(500).json({
            success:false,
            message:"Could not send reset password token"
        })
    }
}

// reset password
exports.resetPassword=async(req,res)=>{
    try{
        //data fetch
    const {password,confirmPassword,token} = req.body;
    //validation
    if(password!==confirmPassword){
        return res.status(401).json({
            success:false,
            message:"Password not matched",
        })
    }
    // console.log("Printing the token received from user",token);
    //get user details from token 
    const userDetails=await User.findOne({token:token});
    //no entry of token in db
    // console.log("User details according to token received",userDetails);
    if(!userDetails){
        return res.status(404).json({
            success:false,
            message:"Token is invalid",
        })
    }
    //token time 
    if(userDetails.resetPasswordExpires<Date.now()){
        return res.status(404).json({
            success:false,
            message:"Token is expired, regenerate token again",
        })
    }
    //password hashing 
    const hashedPassword=await bcrypt.hash(password,10);
    //update password
    // console.log("Hashed Password ",hashedPassword);
    await User.findOneAndUpdate({token:token},{
        password:hashedPassword,
        token:null,
    },{new:true})
    //res return
    return res.status(200).json({
        success:true,
        message:"Password reset successfully",
    }
)
    }catch(err){
        return res.status(500).json({
            success:false,message:"Could not reset password",
        })
    }

}